version: '3.8'

services:
  iptv-sniffer:
    image: thsrite/iptv-sniff:latest
    container_name: iptv-sniffer
    restart: unless-stopped
    ports:
      - "9833:9833"
    volumes:
      - ./screenshots:/app/screenshots
      - ./config:/app/config
#    devices:
      # Uncomment the following line to enable Intel Quick Sync hardware acceleration
      # - /dev/dri:/dev/dri
    environment:
      - PORT=9833
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9833"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
